In [1]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import os
from dotenv import load_dotenv

load_dotenv()

url = URL.create(
    drivername="postgresql+psycopg2",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"), 
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT")),
    database=os.getenv("DB_NAME"),
)

engine = create_engine(url)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
query = """
SELECT *
FROM analytics.customer_department_features
"""

customer_df = pd.read_sql(query, engine)

customer_df.shape

(2232789, 8)

In [5]:
customer_df.sample(5)

,user_id,department,purchase_count,unique_products,reorder_count,avg_cart_position,customer_total_purchases,department_share
1361839,125655,pantry,3,3,0,11.33,119.0,0.0252
1424842,131507,produce,25,16,9,6.44,57.0,0.4386
1904415,175854,breakfast,11,1,10,5.27,251.0,0.0438
137177,12731,snacks,4,2,2,15.00,147.0,0.0272
1162646,107222,beverages,17,1,16,2.24,97.0,0.1753

In [6]:
query = """
SELECT * FROM analytics.product_affinity_features
"""

product_affinity_df = pd.read_sql(query, engine)
product_affinity_df.shape

(3492837, 6)

In [7]:
product_affinity_df.sample(5)

,product_id_a,product_id_b,co_purchase_count,support,confidence,lift
627090,18599,34358,132,0.000041,0.021277,1.868028
2507443,39190,44310,17,0.000005,0.001549,0.829496
985139,481,33352,14,0.000004,0.004636,2.146844
546018,5550,39947,51,0.000016,0.005902,1.688573
2360322,3020,34262,29,0.000009,0.004242,1.141590

In [13]:
product_affinity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3492837 entries, 0 to 3492836
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   product_id_a       int64
 1   product_id_b       int64
 2   co_purchase_count  int64
 3   support            float64
 4   confidence         float64
 5   lift               float64
dtypes: float64(3), int64(3)
memory usage: 159.9 MB

In [15]:
print("Lift > 1      :", len(product_affinity_df[product_affinity_df['lift'] > 1]))
print("Lift > 1.2    :", len(product_affinity_df[product_affinity_df['lift'] > 1.2]))
print("Lift > 1.5    :", len(product_affinity_df[product_affinity_df['lift'] > 1.5]))

print("Confidence > 0.05 :", len(product_affinity_df[product_affinity_df['confidence'] > 0.05]))
print("Confidence > 0.10 :", len(product_affinity_df[product_affinity_df['confidence'] > 0.10]))

print("Co-purchase >= 20 :", len(product_affinity_df[product_affinity_df['co_purchase_count'] >= 20]))
print("Co-purchase >= 50 :", len(product_affinity_df[product_affinity_df['co_purchase_count'] >= 50]))

Lift > 1      : 3133608
Lift > 1.2    : 2930094
Lift > 1.5    : 2586405
Confidence > 0.05 : 204340
Confidence > 0.10 : 71259
Co-purchase >= 20 : 1635864
Co-purchase >= 50 : 572795